### ISSUE TITLE
GetCountOfStringsWithLengthEqualsTo3 issue

### ISSUE THREAD

**Issue by aorgish** [ltanitanil/Net-Training-Tasks#8]
https://github.com/ltanitanil/Net-Training-Tasks/blob/ba8b3195e00e487a525db5f0f6b26f2a84feb7f6/04-Enumerable/Enumerable/Task.cs#L232
Тут Distinct по условию не нужен.

**Comment by ltanitanil** [comment]
Но ведь  в условии сказано: "Returns the number of UNIQUE strings with length=3".

**Comment by aorgish** [comment]
Моя ошибка. Закрываю.
